### ISSUE TITLE
YouTubeChannel2RssFeed Uncaught TypeError: version_compare(): Argument #2 ($version2) must be of type string

### ISSUE THREAD

**Issue by andris155** [cn-tools/cntools_FreshRssExtensions#10]
If I open the Extension menu and the YouTubeChannel2RssFeed extension is installed FreshRSS and php-fpm writes this error:

```
2024/02/22 20:10:20 [error] 1768#1768: *76 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: version_compare(): Argument #2 ($version2) must be of type string, float given in /usr/share/FreshRSS/app/views/extension/index.phtml:64
Stack trace:
#0 /usr/share/FreshRSS/app/views/extension/index.phtml(64): version_compare()
#1 /usr/share/FreshRSS/lib/Minz/View.php(93): include('...')
#2 /usr/share/FreshRSS/lib/Minz/View.php(115): Minz_View->includeFile()
#3 /usr/share/FreshRSS/app/layout/layout.phtml(73): Minz_View->render()
#4 /usr/share/FreshRSS/lib/Minz/View.php(93): include('...')
#5 /usr/share/FreshRSS/lib/Minz/View.php(106): Minz_View->includeFile()
#6 /usr/share/FreshRSS/lib/Minz/View.php(73): Minz_View->buildLayout()
#7 /usr/share/FreshRSS/lib/Minz/Dispatcher.php(59): Minz_View->build()
#8 /usr/share/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
#9 /usr/share/FreshRSS/p/i/index.php(59): Minz_FrontController->run()
#10 {main}
  thrown in /usr/share/FreshRSS/app/views/extension/index.phtml on line 64" while reading upstream, client: 192.168.2.230, server: freshrss.lan, request: "GET /i/?c=extension HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "freshrss.lan"
```

<img width="1007" alt="2024-02-22 (1)" src="https://github.com/cn-tools/cntools_FreshRssExtensions/assets/8324198/0c7cc064-80f4-4101-8203-10983a31cce3">

**Environment information (please complete the following information):**
- Server: Raspberry Pi 5
- OS: Raspberry Pi OS 64 bit (Debian 12 based)
- Browser: Google Chrome 121
- FreshRSS version: 1.23.1
- Database version: PostgreSQL 15.6
- PHP version: PHP 8.2.7

**Comment by cn-tools** [comment]
i changed a little thing at the point of checking the version.
could you update your installation of this add on to the new version and check if it works now?

**Comment by andris155** [comment]
I updated, but still get this error:
```
2024/02/27 18:46:45 [error] 948#948: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: version_compare(): Argument #2 ($version2) must be of type string, float given in /usr/share/FreshRSS/app/views/extension/index.phtml:64
Stack trace:
#0 /usr/share/FreshRSS/app/views/extension/index.phtml(64): version_compare()
#1 /usr/share/FreshRSS/lib/Minz/View.php(93): include('...')
#2 /usr/share/FreshRSS/lib/Minz/View.php(115): Minz_View->includeFile()
#3 /usr/share/FreshRSS/app/layout/layout.phtml(73): Minz_View->render()
#4 /usr/share/FreshRSS/lib/Minz/View.php(93): include('...')
#5 /usr/share/FreshRSS/lib/Minz/View.php(106): Minz_View->includeFile()
#6 /usr/share/FreshRSS/lib/Minz/View.php(73): Minz_View->buildLayout()
#7 /usr/share/FreshRSS/lib/Minz/Dispatcher.php(59): Minz_View->build()
#8 /usr/share/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
#9 /usr/share/FreshRSS/p/i/index.php(59): Minz_FrontController->run()
#10 {main}
  thrown in /usr/share/FreshRSS/app/views/extension/index.phtml on line 64" while reading upstream, client: 192.168.2.230, server: freshrss.lan, request: "GET /i/?c=extension HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "freshrss.lan"
```

**Comment by cn-tools** [comment]
i think now i found the problem ... update once again please

**Comment by cn-tools** [comment]
could you try once again please?

a used json file on github repo FreshRSS/Extensions was updated and i hope it works now.

**Comment by andris155** [comment]
Works perfectly without errors. Thanks!
