### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wikd** [cn-tools/cntools_FreshRssExtensions#34]
In FreshRss 1.25.0-dev, whenever I try adding keywords to the filter and hit submit, it just loads a white page on mobile, and on the computer, it loads an error 500. I checked FreshRss logs, and there is nothing there. The installation check says everything is good, and I've manually checked permissions, etc.

**Comment by marek2001** [comment]
Confirm the same problem. I am using docker latest version.

**Comment by Nyriel** [comment]
I came across the same issue using the docker version.

UI did not give much, ./tmp/FreshRSS.log shows 
"PHP Warning:  preg_match(): Delimiter must not be alphanumeric, backslash, or NUL in /config/www/freshrss/extensions/xExtension-FilterTitle/extension.php on line 66"

Line 66:

65  private function isPatternFound(string $title, string $pattern): bool {
66         if (1 === preg_match($pattern, $title)) {
67             return true;

**Comment by alontraut** [comment]
Hello,

I have been trying everyting I can to configure FilterTitle with no success. I even tried resetting FreshRSS from a new install with all the latest builds. :(

I was really hoping to implement filtering based on article title. Any help would be greatly appreciated.

This is the only error I can identify in the docker logs:
[Wed Jan 08 14:15:06.542947 2025] [php:error] [pid 38:tid 38] [client *IP*:0] PHP Fatal error:  Uncaught TypeError: Minz_Request::paramTextToArray(): Argument #2 ($plaintext) must be of type bool, array given, called in /var/www/FreshRSS/extensions/xExtension-FilterTitle/extension.php on line 15 and defined in /var/www/FreshRSS/lib/Minz/Request.php:148\nStack trace:\n#0 /var/www/FreshRSS/extensions/xExtension-FilterTitle/extension.php(15): Minz_Request::paramTextToArray()\n#1 /var/www/FreshRSS/app/Controllers/extensionController.php(127): FilterTitleExtension->handleConfigureAction()\n#2 /var/www/FreshRSS/lib/Minz/Dispatcher.php(120): FreshRSS_extension_Controller->configureAction()\n#3 /var/www/FreshRSS/lib/Minz/Dispatcher.php(49): Minz_Dispatcher->launchAction()\n#4 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()\n#5 /var/www/FreshRSS/p/i/index.php(59): Minz_FrontController->run()\n#6 {main}\n  thrown in /var/www/FreshRSS/lib/Minz/Request.php on line 148

**Comment by wikd** [comment]
I fiddled with extension.php and fed chatgpt the php errors and somehow it fixed it. No idea what it did but here is the php code if anyone knows what it did. I been using it and it works fine.

<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

class FilterTitleExtension extends Minz_Extension {
    public function init(): void {
        $this->registerTranslates();

        $this->registerHook('entry_before_insert', [$this, 'filterTitle']);
    }

    public function handleConfigureAction(): void {
        $this->registerTranslates();

        if (Minz_Request::isPost()) {
            $configuration = [
                'blacklist' => array_filter(Minz_Request::paramTextToArray('blacklist', true)),
                'mark_as_read' => Minz_Request::paramString('mark_as_read'),
                'whitelist' => array_filter(Minz_Request::paramTextToArray('whitelist', true)),
            ];
            $this->setSystemConfiguration($configuration);
        }
    }

    public function filterTitle($entry) {
        if (is_object($entry) === true) {
            //-- do check BLACKLIST ---------------------------
            $patterns = $this->getSystemConfigurationValue('blacklist') ?? [];
            if (is_array($patterns)) {
                foreach ($patterns as $pattern) {
                    if (self::isPatternFound($entry->title(), $pattern) == true) {
                        if ($this->getSystemConfigurationValue('mark_as_read') == '1') {
                            // add entry into database and mark as read
                            $entry->_isRead(true);
                            return $entry;
                        } else {
                            // add entry into database not allowed
                            Minz_Log::warning(_t('ext.filter_title.warning.not_allowed_keyword', $entry->title()));
                            return null;
                        }
                    }
                }
            }

            //-- do check WHITELIST ---------------------------
            $patterns = $this->getSystemConfigurationValue('whitelist') ?? [];
            if (is_array($patterns)) {
                foreach ($patterns as $pattern) {
                    if (self::isPatternFound($entry->title(), $pattern) == false) {
                        if ($this->getSystemConfigurationValue('mark_as_read') == '1') {
                            // add entry into database and mark as read
                            $entry->_isRead(true);
                            return $entry;
                        } else {
                            // add entry into database not allowed
                            Minz_Log::warning(_t('ext.filter_title.warning.not_allowed_keyword', $entry->title()));
                            return null;
                        }
                    }
                }
            }
        }

        return $entry;
    }

    private function isPatternFound(string $title, string $pattern): bool {
        if (1 === preg_match($pattern, $title)) {
            return true;
        } elseif (strpos($title, $pattern) !== false) {
            return true;
        }
        return false;
    }

    public function getBlacklistData() {
        if ($this->getSystemConfigurationValue('check_type') == '0') {
            // 20240311 - Until version v0.0.2 there was only blacklist OR whitelist availabe
            return implode(PHP_EOL, $this->getSystemConfigurationValue('blacklist_title_keywords') ?? []);
        } else {
            return implode(PHP_EOL, $this->getSystemConfigurationValue('blacklist') ?? []);
        }
    }

    public function getWhitelistData() {
        if ($this->getSystemConfigurationValue('check_type') == '1') {
            // 20240311 - Until version v0.0.2 there was only blacklist OR whitelist availabe
            return implode(PHP_EOL, $this->getSystemConfigurationValue('blacklist_title_keywords') ?? []);
        } else {
            return implode(PHP_EOL, $this->getSystemConfigurationValue('whitelist') ?? []);
        }
    }
}

**Comment by gstorelli** [comment]
> I fiddled with extension.php and fed chatgpt the php errors and somehow it fixed it. No idea what it did but here is the php code if anyone knows what it did. I been using it and it works fine. [Pastebin](https://pastebin.com/KPTeVeKQ)

Tested and it works, I think you can publish it.

Is there a way to set somehow the blacklist on specific category \ feed?

**Comment by mutax** [comment]
Hey,

the call to `Minz_Request::paramTextToArray` is getting two parameters, the name of the variable and an empty array, in the current code.  The empty array needs to go, then it seems to work again.

so in xExtension-FilterTitle/extension.php:

```
            $configuration = [
                'blacklist' => array_filter(Minz_Request::paramTextToArray('blacklist', [])),
                'mark_as_read' => Minz_Request::paramString('mark_as_read'),
                'whitelist' => array_filter(Minz_Request::paramTextToArray('whitelist', [])),
            ];
```
becomes
```
            $configuration = [
                'blacklist' => array_filter(Minz_Request::paramTextToArray('blacklist')),
                'mark_as_read' => Minz_Request::paramString('mark_as_read'),
                'whitelist' => array_filter(Minz_Request::paramTextToArray('whitelist')),
            ];
```

**Comment by Borrower543** [comment]
Still getting this error when clicking "submit" for blacklist or filtertitle.

**Comment by stunlocked94** [comment]
still getting the issue sadly.
